name: eagle_api
description: A simple backend api framework inspired from express.js
version: 1.0.0
repository: https://github.com/eagle-dart/eagle.git

environment:
  sdk: ^3.5.3
  

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
